server {
    listen 80;

    # Serve React built files
    root /usr/share/nginx/html;
    index index.html;

    # Proxy API calls to backend container
    location /api/ {
        proxy_pass http://backend:5000;
    }

    # For React Router — all non-file URLs serve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
